### PR TITLE
Use ZingIcons font to render icons

### PR DESCRIPTION
**Pull request by iafan**
We want our UI to be rendered correctly on hdpi screens. This commit adds a new font and css file that works as a drop-in replacement to sprite.css.

With this change, we drop old sprite icons and related `make sprites` command entirely. Note that there's still some old code (e.g. terminology editor) that technically references the old icons that this commit removes. We will need to clean up this obsolete functionality separately.

### CODE REVIEW

**Comment by iafan** [comment]
@julen this change should also fix the 'X' close button issue that you were experiencing on FF.

**Comment by iafan** [comment]
I updated the close button to be smaller.

I also fixed the exit button layout issue. I believe this is necessary to easily spot this menu item among others. Yes, as our menu grows, we want users to find this item easily.

As for the multiple MT providers, my plan was and still is to make this a drop-down where you select your preferred provider, and then you have only one button to click (and one keyboard shortcut). I deliberately not addressing this in this PR because we have other translation mode changes unmerged.

**Comment by iafan** [comment]
> docs/icons.rst.inc, the supporting code in docs/conf.py and any references to icons in docs need to be removed too (this is why the build fails).

This has also been fixed.

> Last but not least, having the long .icon-foo, .icon-bar, .icon-.... selector is not scalable. I would suggest to use a generic selector which already exists in css/style.css.

We won't be adding tons of icons, so I don't see much of a problem with the current approach. It is explicit and provides good context for what icons are used. We could move from `.icon-something` to `.icon.something` to save a few lines in the css file, but this also requires changing numerous templates, and can be done separately.

**Comment by julen** [comment]
Before merging, it would be great if you could also review which old styles can be removed, but this looks sleek now, great job! 👍

**Comment by iafan** [comment]
I updated the PR — now all icons are there in the font, and sprites-related functionality and files are gone. I also cleaned up old icons-related CSS that was there in css/style.css.

**Pull request merged**
